import type { Brand, Category, FoodItem } from "@/types/food"

// Datos de categorías con IDs numéricos
export const categories: Category[] = [
  { id: 1, name: "Frutas" },
  { id: 2, name: "Verduras" },
  { id: 3, name: "Carnes" },
  { id: 4, name: "Lácteos" },
  { id: 5, name: "Cereales" },
  { id: 6, name: "Legumbres" },
  { id: 7, name: "Frutos secos" },
]

// Datos de marcas
export const brands: Brand[] = [
  { id: "1", name: "Hacendado" },
  { id: "2", name: "Pescanova" },
  { id: "3", name: "Danone" },
  { id: "4", name: "Bimbo" },
  { id: "5", name: "Nestlé" },
]

// Datos de alimentos actualizados con fibra y agua
export const foods: FoodItem[] = [
  {
    id: "1",
    name: "Pollo, pechuga",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    water: 65,
    categoryId: 3, // Carnes
    portion: 100,
    unit: "g",
    price: 8.99,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "2",
    name: "Arroz blanco",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    water: 12,
    categoryId: 5, // Cereales
    portion: 100,
    unit: "g",
    price: 1.25,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "3",
    name: "Plátano",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    water: 74,
    categoryId: 1, // Frutas
    portion: 100,
    unit: "g",
    price: 1.99,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "4",
    name: "Huevo entero",
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0,
    water: 76,
    categoryId: 4, // Lácteos
    portion: 60, // Un huevo mediano
    unit: "g",
    price: 0.25,
    priceUnit: "unit",
    state: "raw",
  },
  {
    id: "5",
    name: "Leche entera",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    water: 88,
    categoryId: 4, // Lácteos
    brandId: "1",
    portion: 100,
    unit: "ml",
    price: 0.95,
    priceUnit: "l",
    state: "processed",
  },
  {
    id: "6",
    name: "Atún en agua",
    calories: 109,
    protein: 24,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    water: 70,
    categoryId: 3, // Carnes
    brandId: "2",
    portion: 100,
    unit: "g",
    price: 12.5,
    priceUnit: "kg",
    state: "processed",
  },
  {
    id: "7",
    name: "Aguacate",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    water: 73,
    categoryId: 1, // Frutas
    portion: 100,
    unit: "g",
    price: 4.99,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "8",
    name: "Pan integral",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.5,
    fiber: 7,
    water: 38,
    categoryId: 5, // Cereales
    portion: 100,
    unit: "g",
    price: 2.5,
    priceUnit: "kg",
    state: "processed",
  },
  {
    id: "9",
    name: "Huevos (Docena)",
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0,
    water: 76,
    categoryId: 4, // Lácteos
    portion: 60, // Un huevo mediano
    unit: "g",
    price: 2.75,
    priceUnit: "pack",
    packSize: 12,
    state: "raw",
  },
  {
    id: "10",
    name: "Lentejas",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    water: 70,
    categoryId: 6, // Legumbres
    portion: 100,
    unit: "g",
    price: 1.8,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "11",
    name: "Almendras",
    calories: 576,
    protein: 21,
    carbs: 22,
    fat: 49,
    fiber: 12.5,
    water: 5,
    categoryId: 7, // Frutos secos
    portion: 100,
    unit: "g",
    price: 12.99,
    priceUnit: "kg",
    state: "raw",
  },
  {
    id: "12",
    name: "Espinacas",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    water: 91,
    categoryId: 2, // Verduras
    portion: 100,
    unit: "g",
    price: 2.49,
    priceUnit: "kg",
    state: "raw",
  },
]

